services:
  loadbalancer:
    build:
      context: .
    networks:
      - app-network
    ports:
      - "8080:8080"
    labels:
      - "lg.BalanceAlgorithm=roundrobin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/app/docker-compose.yaml

  backend:
    build:
      context: ./test
    networks:
      - app-network
    ports:
      - "8081-8089:8081"
    labels:
      - "lg.monitor=true"
      - "lg.min.replicas=1"
      - "lg.max.replicas=3"
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  app-network:
    driver: bridge

